-- Session Store for Express
CREATE TABLE IF NOT EXISTS "store" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "store" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "store" ("expire");

-- Users
-- id is the Google-Provided user id
CREATE TABLE IF NOT EXISTS "users"
(
    id text NOT NULL,
    username text,
    email text,
    rate numeric NOT NULL DEFAULT 60.00,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- Students
CREATE TABLE IF NOT EXISTS "students"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 100 MAXVALUE 2147483647 CACHE 1 ),
    fname text,
    lname text,
    active boolean NOT NULL DEFAULT true,
    rate numeric,
    gid text NOT NULL REFERENCES users ON DELETE CASCADE,
    CONSTRAINT students_pkey PRIMARY KEY (id)
);

-- Class sessions
CREATE TABLE IF NOT EXISTS sessions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    student bigint NOT NULL REFERENCES students ON DELETE CASCADE,
    in_time timestamp with time zone,
    out_time timestamp with time zone,
    rate numeric,
    paid boolean NOT NULL DEFAULT false,
    gid text NOT NULL REFERENCES users,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);
